<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\Pengguna;
use App\Models\Kategori;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run(): void
    {
        $kategori = Kategori::firstOrCreate(['id' => 1], ['nama' => 'Pantai']);

        $kategori = Kategori::firstOrCreate(['id' => 2], ['nama' => 'Gunung']);

        $kategori = Kategori::firstOrCreate(['id' => 3], ['nama' => 'Budaya']);

        $kategori = Kategori::firstOrCreate(['id' => 4], ['nama' => 'Kuliner']);

         // Tambahkan data pengguna langsung di sini
         DB::table('penggunas')->insert([
            [
                'nama' => 'Orell',
                'email' => 'orell@example.com',
                'password' => Hash::make('password123'), // Hash untuk password
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bunga',
                'email' => 'ungak@gmail.com',
                'password' => Hash::make('234'), // Hash untuk password
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        DB::table('wisatas')->insert([
            ['nama_wisata' => 'Pantai Nusa Dua', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai eksklusif dengan pasir putih dan air yang jernih.', 'id_kategori' => 1, 'foto' => 'pantainusadua.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Papuma', 'lokasi' => 'Jember, Indonesia', 'deskripsi' => 'Pantai dengan pasir putih dan batu karang yang indah.', 'id_kategori' => 1, 'foto' => 'papuma.webp', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Gigi Hiu', 'lokasi' => 'Lampung, Indonesia', 'deskripsi' => 'Pantai dengan tebing-tebing batu unik menyerupai gigi hiu.', 'id_kategori' => 1, 'foto' => 'gigi hiu.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Ujung Genteng', 'lokasi' => 'Sukabumi, Indonesia', 'deskripsi' => 'Pantai tenang dengan pasir putih dan ombak yang cocok untuk berselancar.', 'id_kategori' => 1, 'foto' => 'ujung genteng.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Karang Bolong', 'lokasi' => 'Banten, Indonesia', 'deskripsi' => 'Pantai dengan batu karang besar berlubang yang ikonik.', 'id_kategori' => 1, 'foto' => 'karang bolong.jpeg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Pink', 'lokasi' => 'Lombok, Indonesia', 'deskripsi' => 'Pantai unik dengan pasir berwarna pink yang langka.', 'id_kategori' => 1, 'foto' => 'pink beach.webp', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Sorake', 'lokasi' => 'Nias, Indonesia', 'deskripsi' => 'Pantai terkenal dengan ombak tinggi yang cocok untuk selancar.', 'id_kategori' => 1, 'foto' => 'sorake.jpg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Parangtritis', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Pantai legendaris dengan ombak besar dan mitos Nyi Roro Kidul.', 'id_kategori' => 1, 'foto' => 'parangtritis.jpg', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Kuta', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai populer dengan ombak yang cocok untuk berselancar.', 'id_kategori' => 1, 'foto' => 'pantai kuta.webp', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Sanur', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai tenang dengan pemandangan matahari terbit yang indah.', 'id_kategori' => 1, 'foto' => 'pantai sanur.avif', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Ancol', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Pantai rekreasi di kawasan wisata Ancol.', 'id_kategori' => 1, 'foto' => 'ancol.avif', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Kartini', 'lokasi' => 'Jawa Tengah, Indonesia', 'deskripsi' => 'Pantai dengan sejarah R.A. Kartini dan keindahan lautnya.', 'id_kategori' => 1, 'foto' => 'kartini.webp', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Kelinking', 'lokasi' => 'Nusa Penida, Indonesia', 'deskripsi' => 'Pantai tersembunyi dengan pemandangan tebing spektakuler.', 'id_kategori' => 1, 'foto' => 'pantaikelinking2.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Pangandaran', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Pantai eksotis dengan pemandangan alam yang memukau.', 'id_kategori' => 1, 'foto' => 'pangandaran.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Pandawa', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai tersembunyi dengan tebing batu kapur yang megah.', 'id_kategori' => 1, 'foto' => 'pantaipandawa.webp', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Sawarna', 'lokasi' => 'Banten, Indonesia', 'deskripsi' => 'Pantai alami dengan pasir putih dan ombak yang indah.', 'id_kategori' => 1, 'foto' => 'sawarna.webp', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Drini', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Pantai dengan pulau karang unik dan air jernih.', 'id_kategori' => 1, 'foto' => 'drini.jpg', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Seminyak', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai dengan suasana mewah dan sunset yang mempesona.', 'id_kategori' => 1, 'foto' => 'pantaiseminyak.jpeg', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Trikora', 'lokasi' => 'Kepulauan Riau, Indonesia', 'deskripsi' => 'Pantai indah dengan pasir putih dan air biru jernih.', 'id_kategori' => 1, 'foto' => 'trikora.jpeg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Suluban', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai tersembunyi dengan gua batuan yang unik.', 'id_kategori' => 1, 'foto' => 'suluban.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Padang Padang', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai kecil dengan pasir putih dan ombak yang cocok untuk berselancar.', 'id_kategori' => 1, 'foto' => 'pantaipadangpadang.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Green Bowl', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai tersembunyi dengan gua batu dan ombak besar.', 'id_kategori' => 1, 'foto' => 'greenbowl.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Jimbaran', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai terkenal dengan restoran seafood tepi pantai.', 'id_kategori' => 1, 'foto' => 'jimbaran.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Tegal Wangi', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai romantis dengan pemandangan sunset menawan.', 'id_kategori' => 1, 'foto' => 'tegalwangi.jpeg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Seruni', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Pantai indah dengan air laut biru jernih.', 'id_kategori' => 1, 'foto' => 'seruni.jpg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Tanjung Aan', 'lokasi' => 'Lombok, Indonesia', 'deskripsi' => 'Pantai eksotis dengan pasir putih halus.', 'id_kategori' => 1, 'foto' => 'tanjung aan.webp', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Mawun', 'lokasi' => 'Lombok, Indonesia', 'deskripsi' => 'Pantai berbentuk teluk dengan ombak yang tenang.', 'id_kategori' => 1, 'foto' => 'mawun.jpg', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Batu Berlayar', 'lokasi' => 'Belitung, Indonesia', 'deskripsi' => 'Pantai dengan formasi batu granit unik di tengah laut.', 'id_kategori' => 1, 'foto' => 'batuberlayar.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Lengkuas', 'lokasi' => 'Belitung, Indonesia', 'deskripsi' => 'Pantai dengan mercusuar bersejarah dan air laut jernih.', 'id_kategori' => 1, 'foto' => 'lengkuas.jpeg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Santolo', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Pantai indah dengan pemandangan sunrise yang memukau.', 'id_kategori' => 1, 'foto' => 'santolo.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Sire', 'lokasi' => 'Lombok, Indonesia', 'deskripsi' => 'Pantai dengan pasir putih dan pemandangan Gunung Rinjani.', 'id_kategori' => 1, 'foto' => 'sire.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Banyu Tibo', 'lokasi' => 'Pacitan, Indonesia', 'deskripsi' => 'Pantai unik dengan air terjun langsung ke laut.', 'id_kategori' => 1, 'foto' => 'banyutibo.webp', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Watu Lumbung', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Pantai dengan batu karang besar dan suasana alami.', 'id_kategori' => 1, 'foto' => 'watulumbung.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Klayar', 'lokasi' => 'Pacitan, Indonesia', 'deskripsi' => 'Pantai dengan batu karang unik dan suara seruling laut.', 'id_kategori' => 1, 'foto' => 'klayar.jpg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Wediombo', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai luas dengan laguna alami.', 'id_kategori' => 1, 'foto' => 'wediombo.jpg', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Timang', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai terkenal dengan jembatan gantung dan gondola kayu.', 'id_kategori' => 1, 'foto' => 'timang.jpg', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Indrayanti', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai bersih dengan restoran dan fasilitas lengkap.', 'id_kategori' => 1, 'foto' => 'indrayanti.webp', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Baron', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai dengan muara sungai air tawar.', 'id_kategori' => 1, 'foto' => 'baron.webp', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Krakal', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai dengan batu karang panjang dan ombak cocok untuk surfing.', 'id_kategori' => 1, 'foto' => 'krakal.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Kukup', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai dengan pulau kecil dan jembatan penghubung.', 'id_kategori' => 1, 'foto' => 'kukup.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Sepanjang', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai dengan garis pantai panjang dan pasir putih.', 'id_kategori' => 1, 'foto' => 'sepanjang.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Sadranan', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai terkenal untuk snorkeling dengan terumbu karang indah.', 'id_kategori' => 1, 'foto' => 'sadranan.png', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Slili', 'lokasi' => 'Gunung Kidul, Indonesia', 'deskripsi' => 'Pantai kecil dengan pemandangan indah dan suasana tenang.', 'id_kategori' => 1, 'foto' => 'slili.webp', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Serangan', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai cocok untuk berselancar dan melihat penyu.', 'id_kategori' => 1, 'foto' => 'serangan.webp', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Melasti', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai dengan tebing tinggi dan air laut jernih.', 'id_kategori' => 1, 'foto' => 'pantai melasti.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Nusa Penida', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pantai terkenal dengan tebing dan air biru jernih.', 'id_kategori' => 1, 'foto' => 'nusapenida.webp', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Nongsa', 'lokasi' => 'Batam, Indonesia', 'deskripsi' => 'Pantai dengan pemandangan Singapura dan resort mewah.', 'id_kategori' => 1, 'foto' => 'nongsa.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pantai Tanjung Kelayang', 'lokasi' => 'Belitung, Indonesia', 'deskripsi' => 'Pantai dengan batu granit besar dan pasir putih halus.', 'id_kategori' => 1, 'foto' => 'tanjungklyng.webp', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],

            ['nama_wisata' => 'Gunung Rinjani', 'lokasi' => 'Lombok, Indonesia', 'deskripsi' => 'Gunung berapi tertinggi kedua di Indonesia dengan pemandangan spektakuler.', 'id_kategori' => 2, 'foto' => 'rinjani.jpg', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Bromo', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung berapi aktif yang terkenal dengan pemandangan matahari terbit.', 'id_kategori' => 2, 'foto' => 'bromo.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Merbabu', 'lokasi' => 'Jawa Tengah, Indonesia', 'deskripsi' => 'Gunung dengan jalur pendakian yang menantang dan panorama alam yang indah.', 'id_kategori' => 2, 'foto' => 'merbabu.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Semeru', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung tertinggi di Pulau Jawa dengan kawah yang aktif.', 'id_kategori' => 2, 'foto' => 'semeru.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Prau', 'lokasi' => 'Dieng, Indonesia', 'deskripsi' => 'Gunung dengan pemandangan padang bunga dan sunrise terbaik.', 'id_kategori' => 2, 'foto' => 'prau.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Slamet', 'lokasi' => 'Jawa Tengah, Indonesia', 'deskripsi' => 'Gunung tertinggi di Jawa Tengah dengan trek yang menantang.', 'id_kategori' => 2, 'foto' => 'slamet.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Lawu', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung bersejarah dengan banyak situs peninggalan kerajaan.', 'id_kategori' => 2, 'foto' => 'lawu.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Gede', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan keanekaragaman hayati yang tinggi dan trek yang menarik.', 'id_kategori' => 2, 'foto' => 'gede2.jpg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Pangrango', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung yang berbatasan dengan Gunung Gede dan memiliki puncak tertinggi.', 'id_kategori' => 2, 'foto' => 'pangrango.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Ciremai', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung tertinggi di Jawa Barat dengan hutan lebat dan jalur pendakian menantang.', 'id_kategori' => 2, 'foto' => 'ciremai.jpeg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Sumbing', 'lokasi' => 'Jawa Tengah, Indonesia', 'deskripsi' => 'Gunung dengan pemandangan kawah yang indah di puncaknya.', 'id_kategori' => 2, 'foto' => 'sumbing.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Sindoro', 'lokasi' => 'Jawa Tengah, Indonesia', 'deskripsi' => 'Gunung kembar dari Gunung Sumbing dengan jalur pendakian yang indah.', 'id_kategori' => 2, 'foto' => 'sindoro.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Kerinci', 'lokasi' => 'Sumatera Barat, Indonesia', 'deskripsi' => 'Gunung berapi tertinggi di Indonesia dengan pemandangan luar biasa.', 'id_kategori' => 2, 'foto' => 'kerinci.jpg', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Argopuro', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung dengan jalur pendakian terpanjang di Pulau Jawa.', 'id_kategori' => 2, 'foto' => 'argopuro.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Raung', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung dengan kaldera luas dan medan pendakian yang ekstrem.', 'id_kategori' => 2, 'foto' => 'raung.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Ijen', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung yang terkenal dengan fenomena api biru di kawahnya.', 'id_kategori' => 2, 'foto' => 'ijen.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Dempo', 'lokasi' => 'Sumatera Selatan, Indonesia', 'deskripsi' => 'Gunung dengan kebun teh luas dan panorama yang indah.', 'id_kategori' => 2, 'foto' => 'dempo.jpg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Tambora', 'lokasi' => 'Nusa Tenggara Barat, Indonesia', 'deskripsi' => 'Gunung yang terkenal dengan letusan dahsyat pada tahun 1815.', 'id_kategori' => 2, 'foto' => 'tambora.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Papandayan', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan kawah aktif dan pemandangan hutan mati yang unik.', 'id_kategori' => 2, 'foto' => 'papandayan.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Galunggung', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan kawah besar yang pernah meletus dahsyat.', 'id_kategori' => 2, 'foto' => 'galunggung.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Arjuno', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung dengan jalur pendakian yang menantang dan panorama hutan yang lebat.', 'id_kategori' => 2, 'foto' => 'arjuno.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Welirang', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung yang terkenal dengan aktivitas pertambangan belerang.', 'id_kategori' => 2, 'foto' => 'welirang.jpeg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Wilis', 'lokasi' => 'Jawa Timur, Indonesia', 'deskripsi' => 'Gunung dengan jalur pendakian yang masih alami dan jarang dijamah.', 'id_kategori' => 2, 'foto' => 'wilis.webp', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Bukit Raya', 'lokasi' => 'Kalimantan Barat, Indonesia', 'deskripsi' => 'Gunung tertinggi di Kalimantan dengan keanekaragaman hayati yang tinggi.', 'id_kategori' => 2, 'foto' => 'bukitraya.jpg', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Marapi', 'lokasi' => 'Sumatera Barat, Indonesia', 'deskripsi' => 'Gunung aktif dengan jalur pendakian yang cukup menantang.', 'id_kategori' => 2, 'foto' => 'marapi.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Sago', 'lokasi' => 'Sumatera Barat, Indonesia', 'deskripsi' => 'Gunung dengan keindahan alam yang masih sangat alami.', 'id_kategori' => 2, 'foto' => 'sago.webp', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Singgalang', 'lokasi' => 'Sumatera Barat, Indonesia', 'deskripsi' => 'Gunung yang dikenal dengan pemandangan Danau Singkarak dari puncaknya.', 'id_kategori' => 2, 'foto' => 'singgalang.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Talang', 'lokasi' => 'Sumatera Barat, Indonesia', 'deskripsi' => 'Gunung dengan pemandangan danau di sekitarnya dan jalur pendakian yang menarik.', 'id_kategori' => 2, 'foto' => 'talang.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Lewotobi', 'lokasi' => 'Nusa Tenggara Timur, Indonesia', 'deskripsi' => 'Gunung kembar dengan pemandangan indah dan aktivitas vulkanik.', 'id_kategori' => 2, 'foto' => 'lewotobi.jpeg', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Egon', 'lokasi' => 'Nusa Tenggara Timur, Indonesia', 'deskripsi' => 'Gunung aktif dengan jalur pendakian yang cukup terjal.', 'id_kategori' => 2, 'foto' => 'egon.jpeg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Mutis', 'lokasi' => 'Nusa Tenggara Timur, Indonesia', 'deskripsi' => 'Gunung tertinggi di Timor Barat dengan ekosistem hutan yang unik.', 'id_kategori' => 2, 'foto' => 'mutis.jpeg', 'rating' => 4.0, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Binaiya', 'lokasi' => 'Maluku, Indonesia', 'deskripsi' => 'Gunung tertinggi di Maluku dengan jalur pendakian yang menantang.', 'id_kategori' => 2, 'foto' => 'binaiya.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Gamalama', 'lokasi' => 'Maluku Utara, Indonesia', 'deskripsi' => 'Gunung yang berada di Pulau Ternate dengan pemandangan laut yang memukau.', 'id_kategori' => 2, 'foto' => 'gamalama.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Dukono', 'lokasi' => 'Maluku Utara, Indonesia', 'deskripsi' => 'Gunung berapi aktif dengan aktivitas erupsi yang cukup sering.', 'id_kategori' => 2, 'foto' => 'dukono.webp', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Soputan', 'lokasi' => 'Sulawesi Utara, Indonesia', 'deskripsi' => 'Gunung dengan jalur pendakian ekstrem dan sering mengalami erupsi.', 'id_kategori' => 2, 'foto' => 'soputan.jpg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Lokon', 'lokasi' => 'Sulawesi Utara, Indonesia', 'deskripsi' => 'Gunung yang terkenal dengan kawah aktif dan panorama indah.', 'id_kategori' => 2, 'foto' => 'lokon.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Mahawu', 'lokasi' => 'Sulawesi Utara, Indonesia', 'deskripsi' => 'Gunung dengan kawah luas dan jalur pendakian yang mudah.', 'id_kategori' => 2, 'foto' => 'mahawu.jpeg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Tangkuban Perahu', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung berapi terkenal dengan kawah yang bisa dikunjungi.', 'id_kategori' => 2, 'foto' => 'tangkubanparahu.webp', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Andong', 'lokasi' => 'Jawa Tengah, Indonesia', 'deskripsi' => 'Gunung kecil dengan jalur pendakian yang ramah pemula.', 'id_kategori' => 2, 'foto' => 'andong.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Ungaran', 'lokasi' => 'Jawa Tengah, Indonesia', 'deskripsi' => 'Gunung dengan pemandangan indah dan situs sejarah di sekitarnya.', 'id_kategori' => 2, 'foto' => 'ungaran.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Guntur', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan jalur pendakian berbatu dan pemandangan spektakuler.', 'id_kategori' => 2, 'foto' => 'guntur.webp', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Cikuray', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan pemandangan sunrise yang memukau.', 'id_kategori' => 2, 'foto' => 'cikuray.webp', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Malabar', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan sejarah peninggalan stasiun radio zaman Belanda.', 'id_kategori' => 2, 'foto' => 'malabar.png', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Latimojong', 'lokasi' => 'Sulawesi Selatan, Indonesia', 'deskripsi' => 'Gunung tertinggi di Sulawesi Selatan dengan jalur pendakian yang menantang.', 'id_kategori' => 2, 'foto' => 'latimojong.jpeg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Salak', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan banyak air terjun dan jalur pendakian yang cukup ekstrem.', 'id_kategori' => 2, 'foto' => 'salak.jpg', 'rating' => 4.3, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Patuha', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan Kawah Putih yang terkenal sebagai destinasi wisata.', 'id_kategori' => 2, 'foto' => 'patuha.jpg', 'rating' => 4.2, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Wayang', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung dengan legenda dan jalur pendakian yang relatif ringan.', 'id_kategori' => 2, 'foto' => 'wayang.jpg', 'rating' => 4.1, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gunung Burangrang', 'lokasi' => 'Jawa Barat, Indonesia', 'deskripsi' => 'Gunung yang cocok untuk pendaki pemula dengan pemandangan indah.', 'id_kategori' => 2, 'foto' => 'burangrang.webp', 'rating' => 4.0, 'created_at' => now(), 'updated_at' => now()],

            ['nama_wisata' => 'Candi Borobudur', 'lokasi' => 'Magelang, Jawa Tengah, Indonesia', 'deskripsi' => 'Candi Buddha terbesar di dunia dengan relief yang kaya sejarah.', 'id_kategori' => 3, 'foto' => 'candi borobudur.jpg', 'rating' => 4.9, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Candi Prambanan', 'lokasi' => 'Sleman, Yogyakarta, Indonesia', 'deskripsi' => 'Kompleks candi Hindu terbesar di Indonesia yang terkenal dengan kisah Roro Jonggrang.', 'id_kategori' => 3, 'foto' => 'prambanan.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Keraton Yogyakarta', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Istana resmi Kesultanan Yogyakarta yang masih aktif hingga saat ini.', 'id_kategori' => 3, 'foto' => 'keraton.webp', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pura Tanah Lot', 'lokasi' => 'Tabanan, Bali, Indonesia', 'deskripsi' => 'Pura di atas batu karang yang menjadi ikon wisata religi di Bali.', 'id_kategori' => 3, 'foto' => 'tanahlot.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pura Besakih', 'lokasi' => 'Karangasem, Bali, Indonesia', 'deskripsi' => 'Pura terbesar dan paling suci di Bali, sering disebut sebagai "Pura Ibu".', 'id_kategori' => 3, 'foto' => 'besakih.webp', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Museum Nasional Indonesia', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Museum yang menyimpan koleksi sejarah dan kebudayaan Indonesia terlengkap.', 'id_kategori' => 3, 'foto' => 'musnas.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Taman Mini Indonesia Indah', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Taman budaya yang menampilkan miniatur keberagaman budaya Indonesia.', 'id_kategori' => 3, 'foto' => 'tmi.jpeg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Candi Mendut', 'lokasi' => 'Magelang, Jawa Tengah, Indonesia', 'deskripsi' => 'Candi Buddha yang memiliki patung Buddha besar di dalamnya.', 'id_kategori' => 3, 'foto' => 'mendut.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Candi Pawon', 'lokasi' => 'Magelang, Jawa Tengah, Indonesia', 'deskripsi' => 'Candi kecil yang berada di antara Borobudur dan Mendut.', 'id_kategori' => 3, 'foto' => 'pawon.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Candi Ratu Boko', 'lokasi' => 'Sleman, Yogyakarta, Indonesia', 'deskripsi' => 'Situs arkeologi berupa reruntuhan istana kuno dengan pemandangan sunset yang indah.', 'id_kategori' => 3, 'foto' => 'ratuboko.jpeg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Candi Sewu', 'lokasi' => 'Sleman, Yogyakarta, Indonesia', 'deskripsi' => 'Kompleks candi Buddha terbesar kedua setelah Borobudur.', 'id_kategori' => 3, 'foto' => 'sewu.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Candi Plaosan', 'lokasi' => 'Sleman, Yogyakarta, Indonesia', 'deskripsi' => 'Candi kembar yang merupakan kombinasi budaya Hindu dan Buddha.', 'id_kategori' => 3, 'foto' => 'plaosan.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Keraton Surakarta', 'lokasi' => 'Surakarta, Jawa Tengah, Indonesia', 'deskripsi' => 'Istana resmi Kasunanan Surakarta yang kaya akan sejarah dan budaya.', 'id_kategori' => 3, 'foto' => 'keratonsurakarta.webp', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Benteng Vredeburg', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Benteng peninggalan Belanda yang kini menjadi museum sejarah.', 'id_kategori' => 3, 'foto' => 'bentengvredeburg.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Taman Sari Yogyakarta', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Bekas taman kerajaan Yogyakarta yang memiliki arsitektur unik.', 'id_kategori' => 3, 'foto' => 'tsyogya.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Masjid Raya Baiturrahman', 'lokasi' => 'Banda Aceh, Indonesia', 'deskripsi' => 'Masjid bersejarah yang menjadi simbol keberanian rakyat Aceh.', 'id_kategori' => 3, 'foto' => 'masjidbaiturahman.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Masjid Istiqlal', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Masjid terbesar di Asia Tenggara yang menjadi ikon nasional.', 'id_kategori' => 3, 'foto' => 'istiqlal.webp', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gereja Blenduk', 'lokasi' => 'Semarang, Jawa Tengah, Indonesia', 'deskripsi' => 'Gereja peninggalan kolonial Belanda dengan arsitektur khas Eropa.', 'id_kategori' => 3, 'foto' => 'blenduk.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Vihara Avalokitesvara', 'lokasi' => 'Serang, Banten, Indonesia', 'deskripsi' => 'Vihara dengan patung Dewi Kwan Im tertinggi di Indonesia.', 'id_kategori' => 3, 'foto' => 'avalokitesvara.webp', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Kampung Adat Baduy', 'lokasi' => 'Banten, Indonesia', 'deskripsi' => 'Permukiman suku Baduy yang masih mempertahankan tradisi leluhur.', 'id_kategori' => 3, 'foto' => 'baduy.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Kampung Naga', 'lokasi' => 'Tasikmalaya, Jawa Barat, Indonesia', 'deskripsi' => 'Desa tradisional yang mempertahankan adat Sunda.', 'id_kategori' => 3, 'foto' => 'naga.webp', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Desa Wae Rebo', 'lokasi' => 'Flores, Nusa Tenggara Timur, Indonesia', 'deskripsi' => 'Desa adat yang terkenal dengan rumah berbentuk kerucut.', 'id_kategori' => 3, 'foto' => 'waerebo.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Desa Sade', 'lokasi' => 'Lombok, Nusa Tenggara Barat, Indonesia', 'deskripsi' => 'Desa adat suku Sasak yang mempertahankan budaya tradisional.', 'id_kategori' => 3, 'foto' => 'sade.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Museum Ullen Sentalu', 'lokasi' => 'Sleman, Yogyakarta, Indonesia', 'deskripsi' => 'Museum yang menampilkan sejarah dan budaya kerajaan Mataram.', 'id_kategori' => 3, 'foto' => 'sentalu.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Museum Wayang', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Museum yang menyimpan koleksi wayang dari berbagai daerah di Indonesia.', 'id_kategori' => 3, 'foto' => 'm-wayang.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Museum Batik Pekalongan', 'lokasi' => 'Pekalongan, Jawa Tengah, Indonesia', 'deskripsi' => 'Museum yang menampilkan koleksi batik khas Pekalongan.', 'id_kategori' => 3, 'foto' => 'm-batikpk.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Museum Sonobudoyo', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Museum yang menyimpan berbagai koleksi budaya dan sejarah Jawa.', 'id_kategori' => 3, 'foto' => 'm-sonobudoyo.webp', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Museum Fatahillah', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Museum Sejarah Jakarta yang terletak di kawasan Kota Tua.', 'id_kategori' => 3, 'foto' => 'm-fatahillah.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Benteng Fort Rotterdam', 'lokasi' => 'Makassar, Sulawesi Selatan, Indonesia', 'deskripsi' => 'Benteng peninggalan Belanda yang kini menjadi museum sejarah.', 'id_kategori' => 3, 'foto' => 'benteng-rotterdam.webp', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Istana Maimun', 'lokasi' => 'Medan, Sumatera Utara, Indonesia', 'deskripsi' => 'Istana peninggalan Kesultanan Deli dengan arsitektur unik.', 'id_kategori' => 3, 'foto' => 'istanamaimun.png', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pagoda Ekayana', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Pagoda yang menjadi pusat kegiatan agama Buddha di Jakarta.', 'id_kategori' => 3, 'foto' => 'pagoda.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Vihara Ksitigarbha Bodhisattva', 'lokasi' => 'Tanjung Pinang, Kepulauan Riau, Indonesia', 'deskripsi' => 'Vihara megah dengan ratusan patung Buddha di dalamnya.', 'id_kategori' => 3, 'foto' => 'ksiti.jpeg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pura Uluwatu', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pura yang terletak di atas tebing dengan pemandangan laut yang indah.', 'id_kategori' => 3, 'foto' => 'uluwatu.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pura Tirta Empul', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pura suci yang terkenal dengan mata airnya untuk ritual pembersihan.', 'id_kategori' => 3, 'foto' => 'tirtaempul.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pura Gunung Kawi', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Kompleks pura kuno yang diukir di dinding batu.', 'id_kategori' => 3, 'foto' => 'purakawi.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pura Lempuyang', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Pura yang terkenal dengan gerbang surga dan pemandangan Gunung Agung.', 'id_kategori' => 3, 'foto' => 'lempuyang.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],

            ['nama_wisata' => 'Gudeg Yu Djum', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Gudeg legendaris khas Yogyakarta dengan cita rasa autentik.', 'id_kategori' => 4, 'foto' => 'gudeg.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Sate Klathak Pak Pong', 'lokasi' => 'Bantul, Yogyakarta, Indonesia', 'deskripsi' => 'Sate kambing muda yang dimasak dengan tusuk besi.', 'id_kategori' => 4, 'foto' => 'sateklatak.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Nasi Padang Sederhana', 'lokasi' => 'Sumatera Barat, Indonesia', 'deskripsi' => 'Hidangan khas Minang dengan cita rasa rempah yang kuat.', 'id_kategori' => 4, 'foto' => 'naspad.jpeg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pempek Pak Raden', 'lokasi' => 'Palembang, Indonesia', 'deskripsi' => 'Pempek khas Palembang dengan kuah cuko yang khas.', 'id_kategori' => 4, 'foto' => 'pempek.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Bakso President', 'lokasi' => 'Malang, Indonesia', 'deskripsi' => 'Bakso legendaris yang terletak di pinggir rel kereta.', 'id_kategori' => 4, 'foto' => 'bakso.png', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Rawon Setan', 'lokasi' => 'Surabaya, Indonesia', 'deskripsi' => 'Rawon dengan kuah hitam khas dan daging empuk.', 'id_kategori' => 4, 'foto' => 'rawon.jpeg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Bebek Sinjay', 'lokasi' => 'Madura, Indonesia', 'deskripsi' => 'Bebek goreng gurih dengan sambal pencit khas.', 'id_kategori' => 4, 'foto' => 'bebeksinjay.webp', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Mochi Lampion Kaswari', 'lokasi' => 'Sukabumi, Indonesia', 'deskripsi' => 'Mochi lembut khas Sukabumi dengan berbagai isian.', 'id_kategori' => 4, 'foto' => 'mocikaswari.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Rujak Cingur', 'lokasi' => 'Surabaya, Indonesia', 'deskripsi' => 'Rujak dengan irisan cingur (moncong sapi) dan bumbu petis.', 'id_kategori' => 4, 'foto' => 'rujakcingur.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Soto Betawi Haji Husen', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Soto khas Betawi dengan kuah santan yang gurih.', 'id_kategori' => 4, 'foto' => 'sotobetawi.jpeg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Es Cendol Elizabeth', 'lokasi' => 'Bandung, Indonesia', 'deskripsi' => 'Es cendol legendaris dengan santan dan gula aren.', 'id_kategori' => 4, 'foto' => 'cendol.webp', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Tahu Pong Semarang', 'lokasi' => 'Semarang, Indonesia', 'deskripsi' => 'Tahu goreng kopong dengan sambal petis khas Semarang.', 'id_kategori' => 4, 'foto' => 'tahupong.jpeg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Lumpia Gang Lombok', 'lokasi' => 'Semarang, Indonesia', 'deskripsi' => 'Lumpia khas Semarang dengan isian rebung dan udang.', 'id_kategori' => 4, 'foto' => 'lumpia.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Sop Konro Karebosi', 'lokasi' => 'Makassar, Indonesia', 'deskripsi' => 'Sop iga khas Makassar dengan kuah rempah yang kuat.', 'id_kategori' => 4, 'foto' => 'sopkonro.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Ayam Betutu Gilimanuk', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Ayam betutu khas Bali dengan bumbu meresap hingga ke tulang.', 'id_kategori' => 4, 'foto' => 'ayambetutu.jpeg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Ikan Bakar Jimbaran', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Ikan bakar segar dengan sambal khas di tepi pantai Jimbaran.', 'id_kategori' => 4, 'foto' => 'ikanbakar.jpeg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Mie Aceh Titi Bobrok', 'lokasi' => 'Aceh, Indonesia', 'deskripsi' => 'Mie Aceh pedas gurih dengan daging atau seafood.', 'id_kategori' => 4, 'foto' => 'mieaceh.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Gulai Tikungan', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Gulai sapi khas Jakarta yang terkenal di kawasan Blok M.', 'id_kategori' => 4, 'foto' => 'gulai.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Kerak Telor', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Makanan khas Betawi dengan telur, beras ketan, dan ebi.', 'id_kategori' => 4, 'foto' => 'keraktelor.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Sate Lilit', 'lokasi' => 'Bali, Indonesia', 'deskripsi' => 'Sate khas Bali dari daging cincang yang dililitkan pada batang serai.', 'id_kategori' => 4, 'foto' => 'satelilit.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Soto Banjar Bang Amat', 'lokasi' => 'Banjarmasin, Indonesia', 'deskripsi' => 'Soto khas Banjar dengan kuah kaya rempah dan ketupat.', 'id_kategori' => 4, 'foto' => 'sotobanjar.jpeg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Bika Ambon Zulaikha', 'lokasi' => 'Medan, Indonesia', 'deskripsi' => 'Kue khas Medan dengan tekstur bersarang dan aroma pandan.', 'id_kategori' => 4, 'foto' => 'bikaambon.jpeg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Mie Kocok Bandung', 'lokasi' => 'Bandung, Indonesia', 'deskripsi' => 'Mie khas Bandung dengan kuah kental dan kikil sapi.', 'id_kategori' => 4, 'foto' => 'miekocok.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Nasi Gandul Pati', 'lokasi' => 'Pati, Indonesia', 'deskripsi' => 'Nasi dengan kuah santan khas Pati yang gurih dan lezat.', 'id_kategori' => 4, 'foto' => 'nasigandul.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Coto Makassar Daeng Tata', 'lokasi' => 'Makassar, Indonesia', 'deskripsi' => 'Coto Makassar dengan kuah rempah dan daging sapi pilihan.', 'id_kategori' => 4, 'foto' => 'cotomk.jpg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Soto Kudus', 'lokasi' => 'Kudus, Indonesia', 'deskripsi' => 'Soto khas Kudus dengan daging sapi atau ayam dan kuah bening.', 'id_kategori' => 4, 'foto' => 'sotokudus.avif', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Bakpia Pathok 25', 'lokasi' => 'Yogyakarta, Indonesia', 'deskripsi' => 'Kue khas Yogyakarta dengan isian kacang hijau yang lembut.', 'id_kategori' => 4, 'foto' => 'bakpia.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Nasi Liwet Solo', 'lokasi' => 'Solo, Indonesia', 'deskripsi' => 'Nasi liwet khas Solo dengan santan gurih, ayam suwir, dan labu siam.', 'id_kategori' => 4, 'foto' => 'liwetsolo.jpeg', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Tahu Gimbal', 'lokasi' => 'Semarang, Indonesia', 'deskripsi' => 'Tahu goreng dengan bakwan udang, telur, dan bumbu kacang khas.', 'id_kategori' => 4, 'foto' => 'tahugimbal.webp', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Sate Maranggi', 'lokasi' => 'Purwakarta, Indonesia', 'deskripsi' => 'Sate khas Purwakarta dengan bumbu khas dan sambal kecap pedas.', 'id_kategori' => 4, 'foto' => 'maranggi.avif', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Bebek Goreng H. Slamet', 'lokasi' => 'Solo, Indonesia', 'deskripsi' => 'Bebek goreng khas dengan sambal korek pedas.', 'id_kategori' => 4, 'foto' => 'bebekgoreng.webp', 'rating' => 4.7, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Pecel Lele Lela', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Lele goreng dengan sambal khas yang menggugah selera.', 'id_kategori' => 4, 'foto' => 'pecellele.webp', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Sop Buntut Bogor Cafe', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Sop buntut legendaris dengan kuah gurih dan daging empuk.', 'id_kategori' => 4, 'foto' => 'sopbuntut.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Serabi Notosuman', 'lokasi' => 'Solo, Indonesia', 'deskripsi' => 'Serabi khas Solo dengan tekstur lembut dan rasa manis gurih.', 'id_kategori' => 4, 'foto' => 'serabi.jpg', 'rating' => 4.6, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Tengkleng Klewer', 'lokasi' => 'Solo, Indonesia', 'deskripsi' => 'Tengkleng kambing khas Solo dengan kuah berbumbu kuat.', 'id_kategori' => 4, 'foto' => 'tengkleng.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Nasi Uduk Kebon Kacang', 'lokasi' => 'Jakarta, Indonesia', 'deskripsi' => 'Nasi uduk khas Jakarta dengan lauk beragam dan sambal kacang.', 'id_kategori' => 4, 'foto' => 'nasiuduk.jpg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Rendang Uni Farah', 'lokasi' => 'Padang, Indonesia', 'deskripsi' => 'Rendang khas Padang dengan daging sapi empuk dan rempah kaya.', 'id_kategori' => 4, 'foto' => 'rendang.jpg', 'rating' => 4.8, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Es Pisang Ijo', 'lokasi' => 'Makassar, Indonesia', 'deskripsi' => 'Hidangan penutup khas Makassar dengan pisang berbalut hijau dan saus santan.', 'id_kategori' => 4, 'foto' => 'espisangijo.jpeg', 'rating' => 4.5, 'created_at' => now(), 'updated_at' => now()],
            ['nama_wisata' => 'Tahu Sumedang', 'lokasi' => 'Sumedang, Indonesia', 'deskripsi' => 'Tahu goreng khas Sumedang yang renyah di luar, lembut di dalam.', 'id_kategori' => 4, 'foto' => 'tahusumedang.jpg', 'rating' => 4.4, 'created_at' => now(), 'updated_at' => now()],

        ]);

        Pengguna::create([
            'nama' => 'zahra',
            'email' => 'zahir@gmail.com',
            'password' => bcrypt(5555),
        ]);

        Pengguna::create([
            'nama' => 'urel',
            'email' => 'urel@gmail.com',
            'password' => bcrypt(4444),
        ]);
    }
}

